module NzPostApi
  VERSION: String
  class Error < ::StandardError
    attr_reader response_http_code: Integer?
    attr_reader response_body: untyped

    def initialize: (?String message, ?response_http_code: Integer, ?response_body: untyped) -> void
  end
end
